version: "3"

services:
  webserver:
    image: cybersiegelab/php_7.1.x:latest
   # build: 
   #   context: ./dockerBin/apache2
    container_name: 'webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql:mysql
    volumes: 
      - ./config/ssl:/etc/apache2/ssl:rw
      - ./www:/var/www/html:rw
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:rw
      - ./config/apacheVhosts:/etc/apache2/sites-enable:rw
      - ./logs/apache2:/var/log/apache2
  mysql:
    build: ./dockerBin/mysql
    container_name: 'mysql'
    restart: 'always'
    volumes: 
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    env_file:
      - .env
    command: mysqld --max_allowed_packet=128M
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - mysql:mysql
    env_file:
      - .env
    ports:
      - '8000:80'
  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "6379:6379"
